services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    volumes:
      - /configs/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    environment:
      - USER_EMAIL=${BESZEL_USERNAME}
      - USER_PASSWORD=${BESZEL_PASSWORD}
      - AUTO_LOGIN=${BESZEL_USERNAME}
    ports:
      - 8090:8090
    volumes:
      - /configs/beszel_server_data/beszel_data:/beszel_data
      - /configs/beszel_server_data/beszel_socket:/beszel_socket
  filebrowser:
    image: gtstef/filebrowser:latest
    container_name: filebrowser
    pull_policy: always
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - FILEBROWSER_CONFIG=/home/filebrowser/data/config.yaml # overrides the default path which is ./config.yaml
      - FILEBROWSER_ADMIN_PASSWORD=${BESZEL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - /data:/druv/data
      - /configs:/druv/configs
      - /home/druv:/druv/home
      - /configs/filebrowser/data:/home/filebrowser/data
    ports:
      - 8091:8091
networks:
  homelab:
    name: ${NETWORK_NAME}
    external: true
